/*
1. MOSTRAR TODOS OS NUMEROS ENTRE UM INTERVALO X, Y ESCOLHIDOS PELO USUARIO, SABENDO X < Y.
2. MOSTRAR TODOS OS NUMEROS PARES DE DE 1 A 20
3. MOSTRAR TODOS OS NUMEROS DIVISIVEIS POR 3 DE 1 A 30
4. CALCULAR A SOMA DOS NUMEROS IMPARES DE 1 A 20
5. CALCULAR A MEDIA DE 10 VALORES
6. VERIFICAR SE UM NUMERO É PRIMO
7. MOSTRAR A SOMA DOS DIVISORES DE UM NUMERO
8. DECOMPOR UM NUMERO EM FATORES EM PRIMOS
9. GERAR A SEQUENCIA DE FIBONACCI
10. CALCULAR A SOMA DE UMA PROGRESSAO ARITMETICA DADO A1, QUANTIDADE DE TERMOS E RAZAO.

 */

public class Media {
    
}
